In [4]:
from sklearn.metrics import confusion_matrix
y_test=[0,0,0,0,0,1,1,1,1,1]
y_pred=[0,1,1,1,1,0,0,0,1,1]
# confusion_matrixで予想と正解を比較する
#　２＊２の行列で結果を返す
#　自動的に昇順比較になる
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(type(cm))

y_test=[1,1,1,1,1,0,0,0,0,0]
y_pred=[1,1,0,0,0,1,1,1,1,0]
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(type(cm))

# ただし、confusion_matrixにラベルをつけるとPositive/Negativeの指定ができる
# ( , , labels=[1,0])
cm=confusion_matrix(y_test,y_pred,labels=[1,0])
print(cm)

[[1 4]
 [3 2]]
<class 'numpy.ndarray'>
[[1 4]
 [3 2]]
<class 'numpy.ndarray'>
[[2 3]
 [4 1]]
