In [1]:
import numpy as np
x=np.array([1,2,3])
print(x)

# 出力するとタテに出てくる
A=np.array([[1,2,3],[4,5,6]])
print(A)
# shapeは行列構造
print(A.shape)

print(A.dtype)

print(A[1,2])
print(A[0])

[1 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
int32
6
[1 2 3]


In [2]:
# スライシングが2次元のまま戻る
A[:,0:1]

array([[1],
       [4]])

In [3]:
# スライシングと要素単独指定だと1次元で戻る
A[:,0]

array([1, 4])

In [4]:
# 配列形状の転置
# rowとcolumnを入れ替える
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
print(A.T.shape)

(3, 2)


In [6]:
# 配列形状 1-3-2
B=np.array([[[1,2],[3,4],[5,6]]])
print(B)
print(B.shape)

[[[1 2]
  [3 4]
  [5 6]]]
(1, 3, 2)


In [7]:
# 配列形状を2-3-1に転置
print(B.T)
print(B.T.shape)

[[[1]
  [3]
  [5]]

 [[2]
  [4]
  [6]]]
(2, 3, 1)


In [8]:
# 要素形状　2-3　を　1-6　にする
print(A.reshape(1,6))
# マイナスにすることで自動的に適切な要素数に変換する
print(A.reshape(1,-1))

[[1 2 3 4 5 6]]
[[1 2 3 4 5 6]]


In [9]:
Ar=A.reshape(1,-1)
Ar

array([[1, 2, 3, 4, 5, 6]])

In [10]:
B=np.ones((2,3))
#　行の結合
print(np.r_[A,B])
#　列での結合
print(np.c_[A,B])

[[1. 2. 3.]
 [4. 5. 6.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3. 1. 1. 1.]
 [4. 5. 6. 1. 1. 1.]]


In [11]:
# 要素番号が同じもの同士で加算
print(A+B)

[[2. 3. 4.]
 [5. 6. 7.]]


In [12]:
print(A-B)

[[0. 1. 2.]
 [3. 4. 5.]]


In [13]:
print(A*B)
print(np.dot(A,B.T))

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6.  6.]
 [15. 15.]]


In [14]:
print(B/A)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [15]:
C=np.array([[1,2,3]])
# Aと形状が違うため2列三要素[[1,2,3][1,2,3]]に拡張する
print(A+C)

[[2 4 6]
 [5 7 9]]


In [16]:
c=np.array([1,2,3])
# Aと形状が違う
print(A+c)

[[2 4 6]
 [5 7 9]]


In [20]:
import numpy as np
# ブール型配列でマスキング！
x=np.array([1,2,3,4,5],dtype="int64")
x3=x>3
print(x3)
x3=x[x>3]
print(x3)

[False False False  True  True]
[4 5]
